services:
  - type: web
    name: quill-blog
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: quill-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: quill-mongodb
    databaseName: quill_blog
    user: quill_user